### PR TITLE
`onClick` listener is a function

### PR DESCRIPTION
**Pull request by behzad888**
fix Expected `onClick` listener to be a function

### CODE REVIEW

**Comment by rnicholus** [comment]
Why is this needed exactly?

**Comment by behzad888** [comment]
It's a bug.
When I use the onClick event as props, I encountered a bug about `onClick listener is a function`, so I think it should be check and use null  instead of undefined.

**Comment by rnicholus** [comment]
I don’t understand. What exactly is logging this message?

**Comment by behzad888** [comment]
Expected `onClick` listener to be a function, instead got a value of `boolean` type.
    in button (created by DeleteButton)
    in DeleteButton (created by Gallery)
    in li (created by Gallery)
...

**Comment by rnicholus** [comment]
Ok, so I guess this is a React warning? ok

**Pull request merged**
