### PR TITLE
changed react transition group version and updated gallery component

### PR DESCRIPTION
**Pull request by shivgarg5676**

### CODE REVIEW

**Comment by rnicholus** [comment]
I'm unable to find time to test this, but would like to merge. Please confirm you've tested in both React v16 and v15. Thanks for all of your work on this!

**Comment by shivgarg5676** [comment]
I have checked only on react v15.4.2 as it was in dev dependencies. All the test cases are getting passed. I will do a quick sanity on react v16. I will comment back

**Comment by shivgarg5676** [comment]
As [this](https://www.npmjs.com/package/react-addons-test-utils) package has been deprecated  and is moved to react-dom/test-utils. We may need to update our entire test suite to run unit tests on react 16. 
As I am a newbie, please guide how to test for react 16.

**Comment by rnicholus** [comment]
I’m not certain this is absolutely needed, but if you want to upgrade the test suite and are running into a specific issue, let me know what the issue is so I can advise.

**Comment by shivgarg5676** [comment]
Please guide how to test for react 16. I have tested by importing to my project and tested manually it is working but i am unable to run test suite using react 16. 

 I tried as follow but failed.
1. Upgraded react and react-dom version to 16.4.1
2. run npm install
3. run test suite.

I am getting following error
`Error: Cannot find module "react-dom/lib/ReactTestUtils"` as this package has been moved to react-dom/react-test-utils.

**Comment by rnicholus** [comment]
>I have read here and there and people say that you need to import react-test-utils from react-dom/test-utils.

That sounds like a good place to start.

**Comment by shivgarg5676** [comment]
I have tested on react 16. all test cases are getting passed on react-16.
Should I commit new test suite working on react 16 or should we keep old test suite for react 16

**Comment by shivgarg5676** [comment]
All of my code in this branch is backwards compatible and is working fine on both react v15 and v16. You can merge this branch, I will create a new branch with the updated test suite.

**Comment by shivgarg5676** [comment]
#206

**Comment by shivgarg5676** [comment]
@rnicholus can you merge this branch now?

**Pull request merged**
