### PR TITLE
React v16 support

### PR DESCRIPTION
**Pull request by Dog**
Attempt to fix peerDependency not met issue I encountered working with the package in React 16.

Mentioned:
https://github.com/FineUploader/react-fine-uploader/issues/166

### CODE REVIEW

**Comment by rnicholus** [comment]
Sorry - is this the only issue you know of blocking React 16 support?

**Comment by rnicholus** [comment]
can someone with a React 16 project confirm that the changes now in this branch are sufficient?

**Comment by rek** [comment]
I only just started using this lib, but so far in my React 16 project I have faced no other problems.

**Comment by rnicholus** [comment]
Great. Thanks for the confirmation @rek. I’ll release this at once then.

**Pull request merged**
