### PR TITLE
Implement initial files thumbnail rendering

### LINKED ISSUE #51: add initial files
http://docs.fineuploader.com/branch/master/api/options.html#session

the session options seem not working

```
const uploader = new FineUploaderTraditional({
    options: {
        chunking: {
            enabled: true,
            concurrent: {
                enabled: true
            },
        },
        session:{
            endpoint: 'http://localhost:8080/list'
        },
        request: {
            endpoint: 'http://localhost:8080/uploads'
        },
        resume: {
            enabled: true
        },
        retry: {
            enableAuto: true,
            showButton: true
        },
        callbacks: {
            onComplete: (id, name, response) => {
                console.log(id,name,response)
                // handle completed upload
            }
        }
    }
})

<Gallery uploader={ uploader } />
```

### PR DESCRIPTION
**Pull request by truztee**
Resolve #51

### CODE REVIEW

**Comment by rnicholus** [comment]
Nice work. Looks good to me. Are you already using these changes in one of your projects?

**Comment by truztee** [comment]
Yes I have a working local copy, I don't want to change my package.json dependency with my fork, so I just copied the build into the node_modules folder. As far as I can tell it's working nicely.

**Comment by rnicholus** [comment]
Awesome. Merging this now, and I'll release as v0.6.0.

**Comment by rnicholus** [comment]
Released! https://github.com/FineUploader/react-fine-uploader/releases/tag/0.6.0

**Comment by rnicholus** [comment]
I'd like to credit you directly for this work in the Twitter announcement. Can you provide your Twitter handle?

**Comment by truztee** [comment]
thanks, I don't have a personal twitter though, just my startup @truztee_online, and we should be the one thanking you, we're getting closer to our own release with your excellent work.

**Comment by rnicholus** [comment]
Always glad to see when one of my projects goes to good use. v1.0 is nearby - [just a few more cases to complete](https://github.com/FineUploader/react-fine-uploader/projects/1).

**Pull request merged**
